# <?php die(); ?>

## 注意：书写时，缩进不能使用 Tab，必须使用空格。并且各条访问规则之间不能留有空行。

#############################
# 访问规则
#############################

# 访问规则示例
#
# admin 名字空间
admin:
  default:
    allow: ACL_EVERYONE
  ALL_CONTROLLERS:
    allow: "ADMIN"
    deny: ACL_NO_ROLE

