# <?php die(); ?>

## 注意：书写时，缩进不能使用 Tab，必须使用空格

#############################
# 数据库设置
#############################

# devel 模式
devel:
  driver:     mysql
  host:       localhost
  login:      root
  password:   
  database:   tea_db
  charset:    utf8
  prefix:     os_

# test 模式
test:
  driver:     mysql
  host:       localhost
  login:      root
  password:   
  database:   tea_db
  charset:    utf8
  prefix:     os_

# deploy 模式
deploy:
  driver:     mysql
  host:       localhost
  login:      root
  password:   
  database:   tea_db
  charset:    utf8
  prefix:     os_

